# Generated by Django 2.2.24 on 2021-07-17 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_customtext_homepage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customtext',
            name='title',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='body',
        ),
        migrations.AddField(
            model_name='customtext',
            name='albama',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='homepage',
            name='texas',
            field=models.TextField(blank=True),
        ),
    ]
